development:
  :address: smtp.server.com
  :port: 25
  :authentication: plain
  :user_name: user
  :password: pass
production:
  :address: mail.zednine.com
  :port: 25
  :authentication: plain
  :user_name: outbound@zednine.com
  :password: NA*AWdCP