development:
  :address: mail.zednine.com
  :port: 25
  :domain: => "zednine.com"
  :authentication: plain
  :user_name: outbound@zednine.com
  :password: NA*AWdCP
production:
  :address: mail.zednine.com
  :port: 25
  :domain: => "zednine.com"
  :authentication: plain
  :user_name: outbound@zednine.com
  :password: NA*AWdCP