development:
  :address: mail.zed9.org
  :port: 25
  :domain: => "zed9.org"
  :authentication: plain
  :user_name: outbound@zednine.com
  :password: NA*AWdCP
production:
  :address: mail.zed9.org
  :port: 25
  :domain: => "zed9.org"
  :authentication: plain
  :user_name: outbound@zednine.com
  :password: NA*AWdCP