<%=chart :column %>

  <%=comp :chart_rect %>
    y:  12

  <%=comp :chart_border %>
    bottom_thickness:   1
    left_thickness:   1
    color:      d9d9d9

  <%=comp :axis_category %>
    size:        14
    color:             545454    
    bold:   false
    margin: false
    font:   HelveticaNeue-Light

  <%=comp :axis_ticks %>
    value_ticks:       true
    major_thickness:       1
    minor_thickness:       0
    position:         inside
    category_ticks:     true
    major_color:      d9d9d9

  <%=comp :axis_value %>
    bold:   false
    value_ticks:       false
    major_thickness:       1
    position:         inside
    category_ticks:     true
    major_color:      d9d9d9
    steps:          4
    size:          14
    color:     545454
    show_min:   false
    
  <%=comp :tooltip %>
    background_color:  f0f0f0
    alpha:                 90
    background_alpha:      90
    color:             545454    
    size:                  18

  <%=comp :chart_grid_h %>
    alpha:      10
    thickness:   0

  # this is the Tooltip position
  <%=comp :chart_label %>
    position:          cursor

  <%=comp :chart_pref %>
    fill_shape:       false
    point_shape:       none
    line_thickness:       2

  <%=comp :chart_type %>

  <%=comp :legend %>
    size:                    13
    alpha:                   75
    line_alpha:               0
    bullet:                line
    fill_alpha:              10
    delay:                    0
    margin:                   5
    line_color:          000000
    height:                   5
    color:               aabbcc
    fill_color:          000000
    duration:               0.5
    line_thickness:           0
    transition:        dissolve
    #width:                  320
    layout:                 hide

  <%=comp :series_color %>
    colors: 25a1d6

